### ISSUE TITLE
Add VIRTUALB_DEFAULT_PYTHON env variable

### ISSUE THREAD

**Issue by tomplex** [tomplex/virtualb#13]
This will allow users to specify the path to a custom default Python installation. Useful on Ubuntu where the system python is python2 (and the user wishes to default to python3.x).

**Comment by awburgess** [comment]
I assume the idea would be to also be able to declare the version on the fly:

e.g.

```bash
VIRTUALB_DEFAULT_PYTHON=2.7 vb new yo_momma
```
?

**Comment by tomplex** [comment]
Not really; users can already specify using the `-p` flag, like `vb new some_env -p python3.6`. The thought would be that `virtualenv` will default to `python`, so the user could specify ` VIRTUALB_DEFAULT_PYTHON=/usr/local/bin/python3.6` in their `~/.bashrc`and never need use the `-p` flag if they're going to be using `python3.6` 95% of the time.

**Comment by tomplex** [comment]
Added in recent [update](https://github.com/tomplex/virtualb/commit/cb3b240741ab8b1e7a699a4928515eac2ff212d6).
