### ISSUE TITLE
Add `install` command to install a package in a specific environment

### ISSUE THREAD

**Issue by tomplex** [tomplex/virtualb#4]

**Comment by awburgess** [comment]
Perhaps a task for after but what about the ability to install a package to multiple envs?

**Comment by tomplex** [comment]
To me, that would be best expressed as multiple options, so it can be arbitrary. Something like:

`vb install --env/-e [env] -e [env] -p [package] -p [package] -p [package]`

I'm not sure I love how it looks, but it would accomplish the same thing.

**Comment by tomplex** [comment]
I ended up going with the following syntax:

```bash
vb install <virtualenv> [...virtualenv] <package or requirements file> 
```

**Comment by tomplex** [comment]
Added in recent [update](https://github.com/tomplex/virtualb/commit/cb3b240741ab8b1e7a699a4928515eac2ff212d6).
