### ISSUE TITLE
Add command to create requirements.txt

### ISSUE THREAD

**Issue by tomplex** [tomplex/virtualb#7]
maybe `vb requires`?

**Comment by awburgess** [comment]
So ```pip freeze > requirements.txt``` is the goal? I like the naming convention

**Comment by tomplex** [comment]
Yes, essentially. Want to take this one?

**Comment by tomplex** [comment]
Not sure if it's really necessary since we already have `vb freeze`. Maybe the better option is to add an arg to `vb freeze` that creates a `requirements.txt`?

**Comment by tomplex** [comment]
Added in recent [update](https://github.com/tomplex/virtualb/commit/cb3b240741ab8b1e7a699a4928515eac2ff212d6).
